#!/bin/bash -e

# build
#	Simple wiringPi build and install script
#
#	Copyright (c) 2012-2015 Gordon Henderson
#################################################################################
# This file is part of wiringPi:
#	A "wiring" library for the Raspberry Pi
#
#    wiringPi is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Lesser General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    wiringPi is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Lesser General Public License for more details.
#
#    You should have received a copy of the GNU Lesser General Public License
#    along with wiringPi.  If not, see <http://www.gnu.org/licenses/>.
#################################################################################
#
# wiringPi is designed to run on a Raspberry Pi only.
#	However if you're clever enough to actually look at this script to
#	see why it's not building for you, then good luck.
#
#	To everyone else: Stop using cheap alternatives. Support the
#	Raspberry Pi Foundation	as they're the only ones putting money
#	back into education!
#################################################################################

check_make_ok() {
  if [ $? != 0 ]; then
    echo ""
    echo "Make Failed..."
    echo "Please check the messages and fix any problems. If you're still stuck,"
    echo "then please email all the output and as many details as you can to"
    echo "  projects@drogon.net"
    echo ""
    exit 1
  fi
}

if [ -z "$BOARD" ]; then
  echo "No board variable specified"
  exit 1
fi

[[ $BOARD == orangepir1 ]] && BOARD=orangepir1-h2
[[ $BOARD == orangepizero ]] && BOARD=orangepizero-h2
[[ $BOARD == orangepizero-lts ]] && BOARD=orangepizero-h2
[[ $BOARD == orangepipc ]] && BOARD=orangepipc-h3
[[ $BOARD == orangepipch5 ]] && BOARD=orangepipc-h3
[[ $BOARD == orangepipcplus ]] && BOARD=orangepipcplus-h3
[[ $BOARD == orangepiplus2e ]] && BOARD=orangepiplus2e-h3
[[ $BOARD == orangepione ]] && BOARD=orangepione-h3
[[ $BOARD == orangepioneh5 ]] && BOARD=orangepione-h3
[[ $BOARD == orangepilite ]] && BOARD=orangepilite-h3
[[ $BOARD == orangepiplus ]] && BOARD=orangepiplus-h3
[[ $BOARD == orangepizeroplus ]] && BOARD=orangepizeroplus-h5
[[ $BOARD == orangepipc2 ]] && BOARD=orangepipc2-h5
[[ $BOARD == orangepiprime ]] && BOARD=orangepiprime-h5
[[ $BOARD == orangepiwin ]] && BOARD=orangepiwin-a64
[[ $BOARD == orangepiwinplus ]] && BOARD=orangepiwinplus-a64
[[ $BOARD == orangepi3 ]] && BOARD=orangepi3-h6
[[ $BOARD == orangepi3-lts ]] && BOARD=orangepi3-h6
[[ $BOARD == orangepilite2 ]] && BOARD=orangepilite2-h6
[[ $BOARD == orangepioneplus ]] && BOARD=orangepioneplus-h6
[[ $BOARD == orangepizero2 ]] && BOARD=orangepizero2-h616
[[ $BOARD == orangepizero2-lts ]] && BOARD=orangepizero2-h616
[[ $BOARD == orangepizero2-b ]] && BOARD=orangepizero2-h616
[[ $BOARD == orangepizero3 ]] && BOARD=orangepizero2-h616
[[ $BOARD == orangepir1plus ]] && BOARD=orangepir1plus-rk3328
[[ $BOARD == orangepir1plus-lts ]] && BOARD=orangepir1plus-rk3328

export BOARD="${BOARD}"

echo "wiringPi Build script"
echo "====================="
echo

echo "WiringPi Library"
cd wiringPi
make -j5
check_make_ok

echo
echo All Done.
echo ""
echo "NOTE: To compile programs with wiringPi, you need to add:"
echo "    -lwiringPi"
echo "  to your compile line(s) To use the Gertboard, MaxDetect, etc."
echo "  code (the devLib), you need to also add:"
echo "    -lwiringPiDev"
echo "  to your compile line(s)."
echo ""
